In [1]:
import pandas as pd

In [2]:
# Sales data
sales = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "region": ["North", "South", "East", "West", "North", "South"],
    "product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone", "Tablet"],
    "sales": [55000, 30000, 60000, 25000, 35000, 28000]
})

# Customer data
customers = pd.DataFrame({
    "order_id": [101, 102, 103, 107],
    "customer": ["Anita", "Rahul", "Priya", "Kiran"],
    "city": ["Delhi", "Bangalore", "Mumbai", "Chennai"]
})

print("Sales Data:")
display(sales)

print("\nCustomer Data:")
display(customers)

Sales Data:

   order_id region product  sales
0       101  North  Laptop  55000
1       102  South   Phone  30000
2       103   East  Laptop  60000
3       104   West  Tablet  25000
4       105  North   Phone  35000
5       106  South  Tablet  28000

Customer Data:

   order_id customer       city
0       101    Anita      Delhi
1       102    Rahul  Bangalore
2       103    Priya     Mumbai
3       107    Kiran    Chennai

In [3]:
# INNER JOIN
inner_join = pd.merge(
    sales,
    customers,
    on="order_id",
    how="inner"
)

display(inner_join)

   order_id region product  sales customer       city
0       101  North  Laptop  55000    Anita      Delhi
1       102  South   Phone  30000    Rahul  Bangalore
2       103   East  Laptop  60000    Priya     Mumbai

In [4]:
# LEFT JOIN
left_join = pd.merge(
    sales,
    customers,
    on="order_id",
    how="left"
)

display(left_join)

   order_id region product  sales customer       city
0       101  North  Laptop  55000    Anita      Delhi
1       102  South   Phone  30000    Rahul  Bangalore
2       103   East  Laptop  60000    Priya     Mumbai
3       104   West  Tablet  25000      NaN        NaN
4       105  North   Phone  35000      NaN        NaN
5       106  South  Tablet  28000      NaN        NaN

In [5]:
# RIGHT JOIN
right_join = pd.merge(
    sales,
    customers,
    on="order_id",
    how="right"
)

display(right_join)

   order_id region product    sales customer       city
0       101  North  Laptop  55000.0    Anita      Delhi
1       102  South   Phone  30000.0    Rahul  Bangalore
2       103   East  Laptop  60000.0    Priya     Mumbai
3       107    NaN     NaN      NaN    Kiran    Chennai

In [6]:
# OUTER JOIN
outer_join = pd.merge(
    sales,
    customers,
    on="order_id",
    how="outer"
)

display(outer_join)

   order_id region product    sales customer       city
0       101  North  Laptop  55000.0    Anita      Delhi
1       102  South   Phone  30000.0    Rahul  Bangalore
2       103   East  Laptop  60000.0    Priya     Mumbai
3       104   West  Tablet  25000.0      NaN        NaN
4       105  North   Phone  35000.0      NaN        NaN
5       106  South  Tablet  28000.0      NaN        NaN
6       107    NaN     NaN      NaN    Kiran    Chennai

In [7]:
# Pivot table: total sales by region and product
sales_pivot = pd.pivot_table(
    sales,
    values="sales",
    index="region",
    columns="product",
    aggfunc="sum",
    fill_value=0
)

display(sales_pivot)

product  Laptop  Phone  Tablet
region
East      60000      0       0
North     55000  35000       0
South         0  30000   28000
West          0      0   25000

In [8]:
# Pivot table with row and column totals
sales_pivot_totals = pd.pivot_table(
    sales,
    values="sales",
    index="region",
    columns="product",
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name="Total"
)

display(sales_pivot_totals)

product  Laptop  Phone  Tablet   Total
region
East      60000      0       0   60000
North     55000  35000       0   90000
South         0  30000   28000   58000
West          0      0   25000   25000
Total    115000  65000   53000  233000

In [9]:
# Create wide-format sales data
wide_sales = pd.DataFrame({
    "region": ["North", "South", "East"],
    "Laptop": [55000, 0, 60000],
    "Phone": [35000, 30000, 0],
    "Tablet": [0, 28000, 25000]
})

display(wide_sales)

  region  Laptop  Phone  Tablet
0  North   55000  35000       0
1  South       0  30000   28000
2   East   60000      0   25000

In [10]:
# Convert wide format to long format
long_sales = pd.melt(
    wide_sales,
    id_vars=["region"],
    var_name="product",
    value_name="sales"
)

display(long_sales)

  region product  sales
0  North  Laptop  55000
1  South  Laptop      0
2   East  Laptop  60000
3  North   Phone  35000
4  South   Phone  30000
5   East   Phone      0
6  North  Tablet      0
7  South  Tablet  28000
8   East  Tablet  25000

In [11]:
# Reshape long data back into a wide format
reshaped_sales = long_sales.pivot(
    index="region",
    columns="product",
    values="sales"
).fillna(0)

display(reshaped_sales)

product  Laptop  Phone  Tablet
region
East      60000      0   25000
North     55000  35000       0
South         0  30000   28000

In [12]:
# Method chaining: filter, group, calculate, and sort
chained_analysis = (
    sales
    .query("sales > 25000")
    .groupby("region", as_index=False)["sales"]
    .sum()
    .sort_values("sales", ascending=False)
)

display(chained_analysis)

  region  sales
1  North  90000
0   East  60000
2  South  58000

## Conclusion

In this notebook, I practiced advanced Pandas operations including:

- `pd.merge()` for combining DataFrames using different join types.
- `pd.pivot_table()` for summarising sales by region and product.
- `pd.melt()` for converting wide-format data into long-format data.
- `pivot()` for reshaping long data back into wide format.
- Method chaining for performing multiple Pandas operations in a readable workflow.

These operations are useful for combining, reshaping, summarising, and analysing real-world business data.